### ISSUE TITLE
After 0.30, it takes endless time to build nushell on windows wsl

### ISSUE THREAD

**Issue by WindSoilder** [baoyachi/shadow-rs#172]
After I upgrade shadow-rs from 0.29 to 0.31(or 0.30), it takes endless time to build nushell project
```shell
 Updating crates.io index
     Locking 1 package to latest compatible version
    Updating shadow-rs v0.29.0 -> v0.31.1
   Compiling shadow-rs v0.31.1
   Compiling nu-cmd-lang v0.96.2 (/home/windsoilder/projects/nushell/crates/nu-cmd-lang)
    Building [=======================> ] 451/454: nu-cmd-lang(build)
```
And I notice that there are some zombie processes while building it, it works fine on 0.29

![屏幕截图 2024-08-06 071930](https://github.com/user-attachments/assets/75f423de-85cb-4a1e-977a-77895b0379e7)

After confirmed, it can't be reproduce on windows nor mac.

**Comment by baoyachi** [comment]
@WindSoilder 
From version 0.29.0 to 0.30.0 of shadow-rs, the main addition was the ability to retrieve values with the command 'cargo metadata --format-version 1'. Detailed comparison link: https://github.com/baoyachi/shadow-rs/compare/v0.29.0...v0.30.0


To reproduce the issue caused by the change from version 0.29.0 to 0.30.0 of `shadow-rs`, follow these steps:

1. First, enter the Winnow WSL system and in the terminal, run this command to check if it can successfully retrieve the value. If it does not succeed, first check for network issues:
   ```bash
   ~ cargo metadata --format-version 1
   ```

2. Lock the `shadow-rs` version for both dependencies and build-dependencies in your `Cargo.toml` file to version 0.30.0.
   ```toml
   [dependencies]
   ...
   shadow-rs = { version = "=0.30", default-features = false }

   [build-dependencies]
   shadow-rs = { version = "=0.30", default-features = false }
   ```

3. Run `cargo build` to see if the problem you mentioned occurs.

You'll need to perform these steps on your machine. If you encounter any issues or need further assistance, feel free to ask.

**Comment by WindSoilder** [comment]
Hmm...It's strange that I can't reproduce it today.  Sorry for the disturb, I will close it
